
name: Update AI Litigation Index

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas beautifulsoup4 requests

      - name: Run scraper
        run: python scraper.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add litigation_index.csv
          git commit -m "Update litigation index" || echo "No changes to commit"
          git push
          - name: Debug git auth
  run: |
    git config --get remote.origin.url
    git ls-remote origin -h || true

